services:
  carroaki:
    image: php:5.3.29-apache
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    container_name: carroaki
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:5.7
    container_name: carroaki-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: carroaki
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
